/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 skyborg.glb 
*/

import React, { forwardRef, useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Skyborg = forwardRef((props, ref)=>{
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/skyborg.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(()=>{
    actions[props.animationState].play();
    setTimeout(()=>{
      actions[props.animationState].repetitions = 1
      actions[props.animationState].clampWhenFinished = true
    }, 2000)
  },[props, actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Alpha_Joints"
            geometry={nodes.Alpha_Joints.geometry}
            material={materials.Alpha_Joints_MAT}
            skeleton={nodes.Alpha_Joints.skeleton}
          />
          <skinnedMesh
            name="Alpha_Surface"
            geometry={nodes.Alpha_Surface.geometry}
            material={materials.Alpha_Body_MAT}
            skeleton={nodes.Alpha_Surface.skeleton}
          />
        </group>
      </group>
    </group>
  );
})

useGLTF.preload("/skyborg.glb");
export default Skyborg